import Head from "next/head";
import { Inter } from "@next/font/google";
import {
  AppShell,
  Container,
  Flex,
  Footer,
  Header,
  Title,
} from "@mantine/core";
import { TodosList } from "@/component/todosList";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        header={<Header height={60}>{<Title order={1}>Todo</Title>}</Header>}
        footer={<Footer height={60}>{<p>&copy; 2023 Todo</p>}</Footer>}
      >
        <Flex direction="column">
          <Container m={0} h="15rem" mx={"auto"}>
            <Title order={2} color="red" size={"1.5rem"} pb={"1rem"}>
              今日やる
            </Title>
            <TodosList dueDate="today" color="red" />
          </Container>
          <Container m={0} h="15rem" mx={"auto"}>
            <Title order={2} color="orange" size={"1.5rem"} pb={"1rem"}>
              明日やる
            </Title>
            <TodosList dueDate="tomorrow" color="orange" />
          </Container>
          <Container m={0} h="15rem" mx={"auto"}>
            <Title order={2} color="yellow" size={"1.5rem"} pb={"1rem"}>
              今度やる
            </Title>
            <TodosList dueDate="later" color="yellow" />
          </Container>
        </Flex>
      </AppShell>
    </>
  );
};

export default Home;
